### ISSUE TITLE
Update a profile

### ISSUE THREAD

**Issue by ebriand** [Zenika/skillZ#17]
This epic defines that the application will let a user to update their profile.

Associated US :

 - [x] As a user, I want to be able to edit my topics, skills and appetites 
 - [ ] As a user, I can't update someone else's skills / appetite
 - [ ] As a user, I want the update process to be interactive and quick (not a regular form)
 - [ ] As an admin, I want to understand how the users update their profile (behavior)
